### PR TITLE
DOM: support `onClose` event in `dialog` element

### PR DESCRIPTION
**Pull request by Hi-Angel**
See: https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/close_event

### CODE REVIEW

**Comment by pete-murphy** [comment]
Hi, thanks for the PR! The `Generated` module is output from this: https://github.com/purescript-react/purescript-react-basic-dom/blob/main/codegen/consts.js. Could you move this change to that file instead and run the codegen script?

**Comment by Hi-Angel** [comment]
> Hi, thanks for the PR! The `Generated` module is output from this: https://github.com/purescript-react/purescript-react-basic-dom/blob/main/codegen/consts.js. Could you move this change to that file instead and run the codegen script?

Thank you, sure! But how do I regenerate the "Generated.pus" file afterwards?

In fact, I've seen that the file is generated, but I waited for someone to suggest how to make the proper change, because the header of the file has no mention how would one generate it 😅

**Comment by pete-murphy** [comment]
Looks like you should be able to do
```
cd codegen
npm install
node index.js
```

**Comment by Hi-Angel** [comment]
@pete-murphy thank you, done!

I also made a commit that adds an explanation to the header about how to regenerate files, so in the future hopefully contributions from new users will be simpler 😊

**Comment by pete-murphy** [comment]
Thanks again! Released as part of `v7.0.0` (which includes a breaking change to `defaultChecked` type: https://github.com/purescript-react/purescript-react-basic-dom/releases/tag/v7.0.0)

Updating the registry here: https://github.com/purescript/registry/issues/501

**Comment by Hi-Angel** [comment]
@pete-murphy oh, thank you! But what do you think about [this suggestion](https://github.com/purescript-react/purescript-react-basic-hooks/issues/77#issuecomment-2459541968)? Would be cool to have it included as well 😊

**Pull request merged**
