### PR TITLE
Use Spago

### LINKED ISSUE #7: Switch to Spago for tooling
Are we open to switching to Spago for the build tooling? If so, I'd be happy to open a PR with the change.

### PR DESCRIPTION
**Pull request by maxdeviant**
This PR introduces Spago.

I ran `spago build` and it built the project successfully. Not sure what else we'd like to do (if anything) before this is good to merge.

Resolves #7.

### CODE REVIEW

**Comment by maxdeviant** [comment]
@spicydonuts Do you want CI to use `spago build` as well (instead of the current `npx pulp build`)?

**Comment by spicydonuts** [comment]
Ah, I'm not sure we've decided to yet but thank you for the PR! We'll probably want to get `react-basic` `-classic` `-hooks` `-emotion` and `-dnd` at the same time, too.

**Comment by maxdeviant** [comment]
Of course, didn't mean to sound too presumptuous 😅  It does make sense to get all of the related repos at the same time.

I'd be happy to help with migrating the other repos as well, just let me know.

**Comment by spicydonuts** [comment]
I think this is done, I ended up just copying the same pattern across the react-basic repos

**Pull request closed without merging**
